### ISSUE TITLE
Client não inicia;

### ISSUE THREAD

**Issue by charles-silva** [MateusTorquato/chat-tcp-delphi#1]
Está colocando o client para ser conectar a ele mesmo, cada cliente tem um server. Se vc iniciar o server antes vai da erro de porta.

**Comment by MateusTorquato** [comment]
Amigo, desculpa a demora para responder, estou fazendo outros projetos e acabei não me atentando a essa issue. O correto é, primeiro abrir o server, conectar, e depois conectar os clients nesse server. Quando conectar o server ele fica ativo esperando os clients conectarem. A princípio o client precisa estar em outro computador, pois quando eu fiz, coloquei o client na mesma porta do servidor fixo (por isso acontece o problema). No executável do client deveria ter um campo para a porta do servidor, e um para a porta do client, e enviar para o servidor a porta que o client está "escutando" as respostas.

Caso queira implementar e contribuir, sinta-se livre, ficaria muito grato, pois não tenho tempo no momento de implementar isso para você infelizmente.
